# Generated by Django 3.2.8 on 2021-10-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name='Training date'),
        ),
        migrations.AddField(
            model_name='jedi',
            name='weapon',
            field=models.ManyToManyField(to='main_app.Weapon'),
        ),
    ]
