# Generated by Django 3.2.8 on 2021-10-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211022_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jedi',
            old_name='weapon',
            new_name='weapons',
        ),
    ]
